config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root 'posts#index'
  get 'about', to: "pages#about" #get about to pages controller about action
  get 'whatisthis', to: "pages#whatisthis" #get about to pages controller about action

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # map.resources :posts, :collection=>{:test => :get, :do_test => :post}
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  before_create :set_comment_number #before a comment is created define this
  has_rich_text :body #use action text to set up comment body

  #polymorphic comments
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  private

  def set_comment_number
    self.comment_number = users.comment_created #create a new comment in here 
  end
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  # has_many :comments, as: :commentable, dependent: :destroy


  #active storage from rails 5
  # has_one_attached :thumbnail #macro sets up one-to-one mapping between records and files. each record can have one file attached to it
  # has_one_attached :banner
  #action text from rails 6
  has_rich_text :body

  #do some validations
  validates :title, length: { minimum: 5 }
  validates :body,  length: { minimum: 25 }

  self.per_page = 10
  extend FriendlyId
  friendly_id :title, use: :slugged

  #what is this exactly
  def optimized_image(image,x,y)
    return image.variant(resize_to_fill: [x, y]).processed
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy #if u delete a post it will delete all the comments. if u delete user it will delete all the comments lso =
  
  def username
    return self.email.split('@')[0].capitalize
  end

  def comment_created #method called in comment.rb
    self.number_of_comments = number_of_comments + 1 #increments the number of comments
    save #call save
    number_of_comments #return number of comments
  end
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #if the user is not admin will be sent back to home page
    helper_method :is_admin!
    private
    def is_admin!
        if current_user && current_user.admin
        else
            redirect_to root_path
        end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_commentable, only: [:create]
    before_action :set_comment, except: [:create]
    before_action :authenticate_user!

    def new
        # binding.pry
    end

    def create
        @comment = @commentable.comments.build(comment_params)
        @comment.user = current_user
        if params[:comment_id]
            @comment.reply = true
            @comment.save
        end
    end

    def edit
    end

    def update #only gets fired it you are doing a post call - only if patch or put
        # binding.pry
        if @comment.edit_history == ""
            #if \n => replace \n with <br/><hr/> so it looks nice
            @comment.edit_history = "Original: " + @comment.body.body.to_plain_text + "\n" #action text 
        else
            @comment.edit_history = @comment.edit_history + "Edit: " + params[:comment][:body] + "\n"
            @comment.update(comment_params)

        end
    end

    def destroy
    end

    def history
    end

    private
    def comment_params
        params.require(:comment).permit(:body)
    end

    def find_commentable
        if (params[:comment_id]) #reply to another comment
            @commentable = Comment.find_by_id(params[:comment_id]) #params to access forms and url query data
        elsif #comment on post
            @commentable = Post.friendly.find(params[:post_id])
        end
            
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def whatisthis
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  #perform a validation to make sure user is logged in
  before_action :authenticate_user!, except: [:index, :show] #only index and show page does the user need not be logged in
  before_action :is_admin!, except: [:index, :show]


  # GET /posts
  # GET /posts.json
  def index
    # @posts = Post.all.order("created_at DESC").paginate(page: params[:page])
    @posts = Post.paginate(page: params[:page], per_page: 15).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
end
  end 

  # GET /posts/1
  # GET /posts/1.json
  def show
    views = @post.views + 1
    @post.update(views: views)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end


  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    # binding.pry
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      # params.require(:post).permit(:title, :body, :thumbnail, :banner)
      params.require(:post).permit(:title, :body)
    end
  
    def test
    end
    
    def do_test
      name = params[:name]
      phone = params[:phone]
      # do whatever you want...
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_form.html.erb
<div class="row">
    <div class="comment-form">
        <%= form_with model: [commentable, local] do |f|%>
        <%= %>
        <%= f.submit "Post", class: "btn btn-dark float-right" %>
        <%= end%>
    </div>
</div>

app/views/comments/create.js.erb
<%# hey jquery, can you add @comment to the page %>

app/views/comments/edit.js.erb
<%# edit form inside the body of the object %>

app/views/layouts/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-167308723-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());


  gtag('config', 'UA-167308723-1');
</script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Yash Gadodia's Daily Journal </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%# <ul class="navbar-nav mr-auto">
      <li class="nav-item active">  
        <a class="nav-link" href="<%= root_path %>
      <%# </li> %>

    </ul> 
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= whatisthis_path %> ">Read Me</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= about_path %> ">About Me</a>
      </li>
    <% if current_user %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.admin %>
            <a class="dropdown-item" href="posts/new">New Post</a>
            <% end %>
            <a class="dropdown-item" href="<%= edit_user_registration_path %>">Account Settings</a>
            <div class="dropdown-divider"></div>
            <%= link_to "Logout", destroy_user_session_path, class:'dropdown-item', method: :delete %>
            </div>
        </li>
    <% else %>
        <li class="nav-item">
            <%= link_to "Signup", new_user_registration_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to "Signin", new_user_session_path, class:'nav-link' %>
        </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yash Gadodia's Daily Journal.</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/google_analytics'  %> 

    <!--Start of Novocall App Script-->
    <%# <script type='text/javascript'>(function(){var d=document,h=d.getElementsByTagName('head')[0],s=d.createElement('script');s.type='text/javascript';s.async=!0;s.src='https://call.novocall.co/v1/widgets?id=uBaMvmmtkZg';h.appendChild(s)}())</script><!--End of Novocall App Script-->    %>
    <%# navbar partial will be added to every page %>
    
  </head>

  <body>

    <%= render 'layouts/navbar'  %>
    <%# this guy is the master template, this template will be rendered first => yield %>
    <%= yield  %>
  </body>
</html>

app/views/pages/about.html.erb
<%# containers are usd to establish the width of a layout %>
<div class="container jumbotron">
<div class="row">
<h1>About me</h1>
<br>
<hr class="my-4" />
</div>
<div class="row">
<p style="text-align:justify">
The text below was extracted from my Bumble bio. 
It was only up for a day though, before a crippling fear kicked in. 
That I wouldn't get any matches despite putting my best self out there. 
<br>
<br>
So I figured, why not be vulnerable while playing by your own rules?  
<br>
<br>
"I'm a university student, trying to find his place in the world. I would like to climb a tall mountain in Nepal and complete the Ironman someday. 
I would also like to leave the world a better place than it was before I got here. I try to be kind and do right by people." 
<br>
<br>
If you're a prospective employer reading this, it's imperative to explain my love of technology to you. 
I find it has this unilateral ability to impact the lives of millions of people. I would like nothing more than to be a part of that movement. 
If you would like to find out more about me, hyperlinks are below at your convenience - 
</p>
</div>
<hr class="my-4" />
<div class="btn-group" role="group" aria-label="Basic example">
<button type="button" class="btn btn-secondary" onclick="window.location.href = 'https://github.com/yashgadodia';">GitHub</button>
  <button type="button" class="btn btn-secondary" onclick="window.location.href = 'https://www.linkedin.com/in/yashgadodia/';">LinkedIn</button>
  <button type="button" class="btn btn-secondary" onclick="window.location.href = 'https://smumods.com/';">SMUMods</button>
  <button type="button" class="btn btn-secondary" onclick="window.location.href = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';">CV</button>
  <%# <button type="button" class="btn btn-secondary" onclick="window.location.href = 'https://youtube.com/deanin';">My CV</button> %>

</div>

</div>

app/views/pages/whatisthis.html.erb
<%# this is readme doc %>
<div class="container jumbotron">
<div class="row"> 
<h1>Hello, World! </h1> 
<hr class="my-4" />
</div>
<div class="row">
<p style="text-align:justify">
<br>
I'm going to save you some time - most of my writing is terrible. When forced to write daily, most of it will be self-indulgent. 
This blog is a playground for me to experiment and make mistakes. 
<br>
<br>
I figure the only way to get better at writing is to write a lot, even if it is bad. Putting it up online is added motivation in making sure the consistency isn't lost. 
<br>
<br>
Anyway. Every now and then I will write something that (I think) is half-decent. I hope you like it. 
<br>
<br>
<a href = "http://yashgadodia.com/posts/work-from-home-day-47">Work from home day 47 </a>
<br>
<a href = "http://yashgadodia.com/posts/4-180-42">4-180-42 </a>
<br>
<a href = "http://yashgadodia.com/posts/for-7-lifetimes">For 7 lifetimes </a>
<br>
<a href = "http://yashgadodia.com/posts/blm-some-thoughts">BLM-some thoughts </a> 
<br>
<a href = "http://yashgadodia.com/posts/yet-another-post-on-body-positivity">Yet another post on body positivity</a> 
<br>
<a href = "http://yashgadodia.com/posts/indian-sketches">Indian Sketches</a> 
<br>
<a href = "http://yashgadodia.com/posts/i-m-awesome">I'm awesome</a> 
<br>
<a href = "http://yashgadodia.com/posts/nobody-wanna-be-a-frogman-on-a-rainy-day">Nobody wanna be a frogman on a rainy day </a>
<br>



</p>

<hr class="my-4" />
</div>

</div>

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>
  
  <div class="form-inputs">
    <%= f.text_field :title, class:'form-control string' %>
    <%# <%= f.label :thumbnail, class:'form-control' %> 
    <%# <%= f.file_field :thumbnail %> 
    <%# <%= f.label :banner, class:'form-control' %>
    <%# <%= f.file_field :banner %> 
    <%= f.rich_text_area :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/_like_button.html.erb
<div class="like-icon mx-2 <%= 'red' if current_user.favorited?(post) %>" data-id="<%= [post].id %>">
  <i class="fas fa-heart"></i>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<head>
    <style>
        .center {
            margin: auto;
            width: 50%;
            /* border: 3px solid blue;
            padding: 10px; */
        }
        .center-text {
            margin: auto;
            width: 50%;
            border: 3px solid blue;
            padding: 10px;
        }
    </style>
</head>

<div class="container" >
    <div class="card-columns text-center">
        <% @posts.each do |post| %>
                <div class="card" id="my-posts"">
                    <%# <img class="card-img-top" src="<%= url_for post.optimized_image(post.thumbnail, 586, 180)" alt="Blog Post Image Card" /> %> 
                    <div class="card-body">
                        <h5 class="card-title">
                            <%= link_to post.title, post %>
                        </h5>
                        <p class="card-text">
                            <%= post.body.to_plain_text.truncate_words(rand(20..65)) %>
                        </p>
                        <p class="card-text">
                            <small class="text-muted">
                                <%= post.created_at.strftime("%A, %B %e, %Y") %> by
                                <%= post.user.username %> 
                            </small>
                        </p>
                    </div>
                </div>
        <% end %>
    </div>
</div>

<div id="infinite-scrolling">
    <%# this houses pagination controls%>
  <%= will_paginate  %> 
</div>

<%# <div class="row center">
    <div class="digg_pagination center-text">
        <%= will_paginate @posts, :container => false %>
    <%# </div>  %>
<%# </div> %> 

app/views/posts/index.js.erb
$('#my-posts').append('<%= j render @posts %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%# actual banner %>

<%# <div style="width:100%; height: 300px; overflow-y:hidden"> %>
  <%# <%= image_tag(@post.banner, style:'width:100%') %> 
<%# </div> %>

<%# creating content of the actual blog post %>

<div class="container" style="margin-top: 2em">
  <div class="row">
    <div class="jumbotron" style="width:100%">    
      <h1 class="display-4">
        <%= link_to @post.title, root_path %>
      </h1>
      <p class="lead">
        <%= @post.created_at.strftime("%A, %B %e, %Y") %> by <%= @post.user.username %> | <%= pluralize(@post.views, "View") %>
      </p>
      <hr class="my-4" />
      <div class="post_body">
        <%= @post.body %>
      </div>
    <div class="row">
    <% if current_user %>
        <% if current_user.admin %>
            <%# <%= link_to "destroy post", posts_destroy_path(@post), method: :destroy%> 
            <%= link_to "Delete post", @post, method: "delete" %>
            <%= link_to "Edit post", edit_post_path()%>
        <% end %>
    <% end %>
    </div>
    </div>
  </div>
</div>

app/views/posts/toggle_favorite.js.erb
var postId = '<%= @post.id%>'
function toggleLikeButton(postId, innerHTML) {
  let likeButton = document.querySelector(`.like-icon[data-id='${postId}']`)
  likeButton.classList.toggle('red');
}
toggleLikeButton(postId);